export const itemsPengguna = [
  { username: "Samppa Nori", registered: "2012/01/01", role: "Member" },
  { username: "Estavan Lykos", registered: "2012/02/01", role: "Staff" },
  { username: "Chetan Mohamed", registered: "2012/02/01", role: "Admin" },
  { username: "Derick Maximinus", registered: "2012/03/01", role: "Member" },
  { username: "Friderik Dávid", registered: "2012/01/21", role: "Staff" },
  { username: "Yiorgos Avraamu", registered: "2012/01/01", role: "Member" },
  {
    username: "Avram Tarasios",
    registered: "2012/02/01",
    role: "Staff",
    _classes: "table-success",
  },
  { username: "Quintin Ed", registered: "2012/02/01", role: "Admin" },
  { username: "Enéas Kwadwo", registered: "2012/03/01", role: "Member" },
  { username: "Agapetus Tadeáš", registered: "2012/01/21", role: "Staff" },
  {
    username: "Carwyn Fachtna",
    registered: "2012/01/01",
    role: "Member",
    _classes: "table-info",
  },
  { username: "Nehemiah Tatius", registered: "2012/02/01", role: "Staff" },
  { username: "Ebbe Gemariah", registered: "2012/02/01", role: "Admin" },
  { username: "Eustorgios Amulius", registered: "2012/03/01", role: "Member" },
  { username: "Leopold Gáspár", registered: "2012/01/21", role: "Staff" },
  { username: "Pompeius René", registered: "2012/01/01", role: "Member" },
  { username: "Paĉjo Jadon", registered: "2012/02/01", role: "Staff" },
  { username: "Micheal Mercurius", registered: "2012/02/01", role: "Admin" },
  { username: "Ganesha Dubhghall", registered: "2012/03/01", role: "Member" },
  { username: "Hiroto Šimun", registered: "2012/01/21", role: "Staff" },
  { username: "Vishnu Serghei", registered: "2012/01/01", role: "Member" },
  { username: "Zbyněk Phoibos", registered: "2012/02/01", role: "Staff" },
  {
    username: "Einar Randall",
    registered: "2012/02/01",
    role: "Admin",
    _classes: "table-danger",
  },
  { username: "Félix Troels", registered: "2012/03/21", role: "Staff" },
  { username: "Aulus Agmundr", registered: "2012/01/01", role: "Member" },
]

export const itemsProvinsi = [
  { "nama-provinsi": "Samppa Nori" },
  { "nama-provinsi": "Estavan Lykos" },
  { "nama-provinsi": "Chetan Mohamed" },
  { "nama-provinsi": "Derick Maximinus" },
  { "nama-provinsi": "Friderik Dávid" },
  { "nama-provinsi": "Yiorgos Avraamu" },
  {
    "nama-provinsi": "Avram Tarasios",
    _classes: "table-success",
  },
  { "nama-provinsi": "Quintin Ed" },
  { "nama-provinsi": "Enéas Kwadwo" },
  { "nama-provinsi": "Agapetus Tadeáš" },
  {
    "nama-provinsi": "Carwyn Fachtna",
    _classes: "table-info",
  },
  { "nama-provinsi": "Nehemiah Tatius" },
  { "nama-provinsi": "Ebbe Gemariah" },
  { "nama-provinsi": "Eustorgios Amulius" },
  { "nama-provinsi": "Leopold Gáspár" },
  { "nama-provinsi": "Pompeius René" },
  { "nama-provinsi": "Paĉjo Jadon" },
  { "nama-provinsi": "Micheal Mercurius" },
  { "nama-provinsi": "Ganesha Dubhghall" },
  { "nama-provinsi": "Hiroto Šimun" },
  { "nama-provinsi": "Vishnu Serghei" },
  { "nama-provinsi": "Zbyněk Phoibos" },
  {
    "nama-provinsi": "Einar Randall",
    _classes: "table-danger",
  },
  { "nama-provinsi": "Félix Troels" },
  { "nama-provinsi": "Aulus Agmundr" },
];

export const itemsKategori = [
  { "nama-kategori": "Samppa Nori" },
  { "nama-kategori": "Estavan Lykos" },
  { "nama-kategori": "Chetan Mohamed" },
  { "nama-kategori": "Derick Maximinus" },
  { "nama-kategori": "Friderik Dávid" },
  { "nama-kategori": "Yiorgos Avraamu" },
  {
    "nama-kategori": "Avram Tarasios",
    _classes: "table-success",
  },
  { "nama-kategori": "Quintin Ed" },
  { "nama-kategori": "Enéas Kwadwo" },
  { "nama-kategori": "Agapetus Tadeáš" },
  {
    "nama-kategori": "Carwyn Fachtna",
    _classes: "table-info",
  },
  { "nama-kategori": "Nehemiah Tatius" },
  { "nama-kategori": "Ebbe Gemariah" },
  { "nama-kategori": "Eustorgios Amulius" },
  { "nama-kategori": "Leopold Gáspár" },
  { "nama-kategori": "Pompeius René" },
  { "nama-kategori": "Paĉjo Jadon" },
  { "nama-kategori": "Micheal Mercurius" },
  { "nama-kategori": "Ganesha Dubhghall" },
  { "nama-kategori": "Hiroto Šimun" },
  { "nama-kategori": "Vishnu Serghei" },
  { "nama-kategori": "Zbyněk Phoibos" },
  {
    "nama-kategori": "Einar Randall",
    _classes: "table-danger",
  },
  { "nama-kategori": "Félix Troels" },
  { "nama-kategori": "Aulus Agmundr" },
];